sonar.projectKey=fga-eps-mds_2026-2-AnatoQuizUp-BFF
sonar.organization=fga-eps-mds-1
sonar.sources=src
sonar.tests=tests,src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.ts,**/*.d.ts
